# -*- coding: utf-8 -*-
"""my_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BoguDnShN1w5Ny3TlO7xsxCkqWemuxE
"""

def anusha(a,b):
  return a+b